include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    no_leading_underscores_for_local_identifiers: false
    constant_identifier_names: false
    public_member_api_docs: true

# analyzer:
#   exclude:
#     - "**/*.g.dart"
#     - "**/*.freezed.dart"