name: shopify_flutter
description: A Flutter package to seamlessly connect your Shopify store with your app.
version: 2.3.0
homepage: https://github.com/imsujan276/shopify_flutter

tags:
  - shopify
  - shopify_flutter

environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  shared_preferences: ^2.0.20
  intl: ^0.19.0
  url_launcher: ^6.1.10
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # dart run build_runner watch --delete-conflicting-outputs 
  build_runner: ^2.3.3
  freezed: ^2.3.2
  analyzer: ^6.2.0

screenshots:
 - description: 'Search Example of the shopify storefront'
   path: example/screenshot/search.png
